#include "gemm_w4a4.h"

// Host launcher for the Ascend gemm_w4a4 pod.
//
// Phase 1b (current): pack-and-launch skeleton. Hands the params
// struct verbatim to the device kernel, which is a no-op placeholder
// — the goal is to verify the cube/vec launch path itself, not
// numerics. Real grid sizing and per-CTA work assignment land in
// Phase 3.
//
// `aclrtlaunch_svdquant_gemm_w4a4_kernel` is auto-generated by
// ascendc.cmake's host_stub.cpp; its include path is exposed via
// INTERFACE include propagation from the device static lib.

#include <acl/acl.h>
#include "aclrtlaunch_svdquant_gemm_w4a4_kernel.h"

namespace svdquant::ascend {

void gemm_w4a4(const GemmW4A4Params& p, void* stream) {
    // Stage params on the device. The placeholder device kernel
    // doesn't dereference, but later phases will, so wire the H2D
    // copy now.
    void* dev_params = nullptr;
    if (aclrtMalloc(&dev_params, sizeof(GemmW4A4Params),
                    ACL_MEM_MALLOC_HUGE_FIRST) != ACL_SUCCESS) {
        return;
    }
    if (aclrtMemcpy(dev_params, sizeof(GemmW4A4Params),
                    &p, sizeof(GemmW4A4Params),
                    ACL_MEMCPY_HOST_TO_DEVICE) != ACL_SUCCESS) {
        aclrtFree(dev_params);
        return;
    }

    // Single-CTA launch for the smoke. Real M/N grid in Phase 3.
    constexpr uint32_t blockDim = 1;
    aclrtlaunch_svdquant_gemm_w4a4_kernel(
        blockDim, static_cast<aclrtStream>(stream), dev_params);

    // The launch is async; freeing dev_params now races with the
    // kernel reading it. Acceptable for the placeholder (kernel
    // doesn't touch params), but Phase 3 needs a per-stream pool
    // or `aclrtSynchronizeStream` before free. TODO: pool.
    aclrtFree(dev_params);
}

}  // namespace svdquant::ascend
